name: Self hosted deploy/build/start server

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
      - run: pm2 reload about-me-next-js
        env:
          CI: true
