name: CI/CD

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        # install yarn and deps
      - run: npm install -g yarn
      - name: install dependencies
        run: yarn
        # tests
      - name: run tests
        run: yarn testci
        # build
      - name: build
        run: yarn build
        # deploy
      - name: deploy
        run: touch rsync_pass && cat > rsync_pass << "${{ secrets.server_pass }}" && cd build && rsync --archive --compress --delete --password-file=../rsync_pass . ${{ secrets.server__username }}@${{ secrets.server_ip }}:/var/www/${{ secrets.server__folder }}/html/

